export const START    = 'START'
export const SUCCESS  = 'SUCCESS'
export const FAIL     = 'FAIL'

export const REGISTER   = 'REGISTER'
export const LOGIN      = 'LOGIN'
export const LOGOUT     = 'LOGOUT'
export const CHECK_AUTH = 'CHECK_AUTH'

export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_USER_FEEDBACK = 'GET_USER_FEEDBACK'

export const GET_YOUR_DATA = 'GET_YOUR_DATA'

export const CLEAR_AUTH = 'CLEAR_AUTH'

export const LOAD_MARKET_DATA = 'LOAD_MARKET_DATA'

export const CHECK_LIKE = 'CHECK_LIKE'
export const LIKE = 'LIKE'
export const UNLIKE = 'UNLIKE'
export const LOAD_LIKES = 'LOAD_LIKES'
export const CLEAR_LIKES = 'CLEAR_LIKES'

export const SEND_FEEDBACK = 'SEND_FEEDBACK'
export const REPORT_FEEDBACK = 'REPORT_FEEDBACK'
export const CLEAR_REPORT_FEEDBACK = 'CLEAR_REPORT_FEEDBACK'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const LOAD_ONE_PRODUCT = 'LOAD_ONE_PRODUCT'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const ORDER_CREATE = 'ORDER_CREATE'
export const CLEAR_CREATE_ORDER_DATA = 'CLEAR_CREATE_ORDER_DATA'
export const LOAD_ORDERS = 'LOAD_ORDERS'
export const LOAD_ONE_ORDER = 'LOAD_ONE_ORDER'
export const LOAD_ORDER_COMMENTS = 'LOAD_ORDER_COMMENTS'
export const ADD_ORDER_COMMENT = 'CHECK_ORDER_COMMENTS'
export const CLEAR_ORDER_COMMENTS = 'CLEAR_ORDER_COMMENTS'
export const SEND_ORDER_COMMENT = 'SEND_ORDER_COMMENT'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'

export const BAN = 'BAN'
export const UNBAN ='UNBAN'
export const CHECK_BAN = 'CHECK_BAN'
export const LOAD_BANS_LIST = 'LOAD_BANS_LIST'

export const SETTINGS_ACCOUNT = 'SETTINGS_ACCOUNT'
export const CLEAR_SETTINGS_ACCOUNT = 'CLEAR_SETTINGS_ACCOUNT'

export const SETTINGS_PASSWORD = 'SETTINGS_PASSWORD'

export const SETTINGS_COMMUNICATION = 'SETTINGS_COMMUNICATION'

export const SETTINGS_IMAGES_AVATAR_SAVE = 'SETTINGS_IMAGES_AVATAR_SAVE'
export const SETTINGS_IMAGES_AVATAR_REMOVE = 'SETTINGS_IMAGES_AVATAR_REMOVE'

export const SETTINGS_IMAGES_WALLPAPER_SAVE = 'SETTINGS_IMAGES_WALLPAPER_SAVE'
export const SETTINGS_IMAGES_WALLPAPER_REMOVE = 'SETTINGS_IMAGES_WALLPAPER_REMOVE'


export const EMAIL_SEND_CODE = 'EMAIL_SEND_CODE'
export const EMAIL_CONFIRM = 'EMAIL_CONFIRM'


export const SEND_PASSWORD_RESET_CODE = 'SEND_PASSWORD_RESET_CODE'
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
