# Generated by Django 2.0.6 on 2018-07-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='status',
            new_name='mark',
        ),
    ]
