# Generated by Django 2.0.6 on 2018-07-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_feedback', '0004_auto_20180701_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_feedback.Feedback')),
            ],
        ),
    ]
