# Generated by Django 2.0.6 on 2018-07-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_feedback', '0005_feedbackreports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackReports',
            new_name='FeedbackReport',
        ),
    ]
