# Generated by Django 2.0.6 on 2018-07-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_feedback', '0007_auto_20180701_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
