# Generated by Django 2.0.5 on 2018-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_feedback', '0009_auto_20180718_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='reason',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
