# Generated by Django 2.0.6 on 2018-06-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0003_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
