# Generated by Django 2.0.6 on 2018-07-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0004_account_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rating',
        ),
    ]
