# Generated by Django 2.0.6 on 2018-07-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0006_auto_20180701_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='facebook_content_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='instagram_content_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='other_content_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_content_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vk_content_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='youtube_content_type',
        ),
    ]
