# Generated by Django 2.0.6 on 2018-07-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0007_auto_20180704_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
