# Generated by Django 2.0.5 on 2018-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0009_auto_20180715_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='User of SpaceShard', max_length=50),
        ),
    ]
