# Generated by Django 2.0.5 on 2018-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0010_auto_20180718_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='User of MediaMoon', max_length=50),
        ),
    ]
