# Generated by Django 2.0.5 on 2018-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0011_auto_20180725_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='main_lang',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
