# Generated by Django 2.0.6 on 2018-07-28 15:25

import db_account.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0012_account_main_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfileWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.FileField(default='users_avatars/_user_default_avatar.svg', upload_to=db_account.models.RandomFileName('profile_wallpapers/'))),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db_account.Account')),
            ],
        ),
    ]
