# Generated by Django 2.0.6 on 2018-07-28 15:51

import db_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0013_accountprofilewallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofilewallpaper',
            name='wallpaper',
            field=models.FileField(default='profile_wallpapers/_default_profile_wallpaper.svg', upload_to=db_account.models.RandomFileName('profile_wallpapers/')),
        ),
    ]
