# Generated by Django 2.0.6 on 2018-07-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_account', '0016_accountbans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbans',
            options={'verbose_name_plural': 'Account bans'},
        ),
    ]
