# Generated by Django 2.0.6 on 2018-07-01 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_order', '0002_ordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
