# Generated by Django 2.0.6 on 2018-07-01 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_order', '0003_ordercomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
