# Generated by Django 2.0.6 on 2018-07-31 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_order', '0006_auto_20180702_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='from_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='to_user',
            field=models.IntegerField(default=0),
        ),
    ]
