# Generated by Django 2.0.6 on 2018-08-04 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_order', '0008_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
