# Generated by Django 2.0.6 on 2018-06-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_product', '0002_auto_20180630_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name_plural': 'Facebook'},
        ),
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name_plural': 'Instagram'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name_plural': 'Other'},
        ),
        migrations.AlterModelOptions(
            name='twitter',
            options={'verbose_name_plural': 'Twitter'},
        ),
        migrations.AlterModelOptions(
            name='vk',
            options={'verbose_name_plural': 'Vk'},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name_plural': 'Youtube'},
        ),
    ]
