# Generated by Django 2.0.6 on 2018-07-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_product', '0003_auto_20180630_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('second_price', models.IntegerField(default=0)),
                ('price_type', models.IntegerField(default=1)),
                ('auto', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Twitch',
            },
        ),
    ]
