# Generated by Django 2.0.6 on 2018-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_product', '0005_auto_20180704_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='content_type',
            field=models.IntegerField(default=0),
        ),
    ]
