# Generated by Django 2.0.5 on 2018-07-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_product', '0006_other_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='other',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='twitch',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='vk',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='auto',
        ),
    ]
